
- id: arxiv:2403.07592
  type: paper
  image: https://github.com/NEXGEM/TRIPLEX/raw/main/figures/TRIPLEX_main.jpg

- id: doi:10.1038/s41467-021-26788-6
  type: paper
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-021-26788-6/MediaObjects/41467_2021_26788_Fig1_HTML.png?as=webp

- id: doi:10.1158/2159-8290.CD-21-0887
  type: paper
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerdiscovery/12/4/10.1158_2159-8290.cd-21-0887/4/1088fig1.jpeg?Expires=1710306178&Signature=v5FkW3AzkhX2aj9ZvT5K8r7M-gnVgKiMd6Ct-ChSDCK3eqd1t7r4ZFHLNU1M2zH~SFaNNGKJAjPDrpd5tp4a9~9mHfzrB7BZlGnugXhQmjuOmrJx~ZsSjh4fTOE1WYXpRzLFIsasgfFIFh2B3CHPSN~I3uEkbRBMeoSUntpQzgg9ziRJE4jTS9Kge7a91ZJiwl4TW8hb0EMVnOBXWbmmRNNcVenYrftSAO58pKTZskJXAwyNnoLHJpPXHarUhU~zyHXQzy0yZE4e3Ftn5uME2Nq-NzA5fo~MyH9od0nDGIGTUPXYGQWJjkrSzzJ6rz4gJKNhl~NKqtGRQMqX2dwc1g__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1016/j.celrep.2022.110418
  type: paper
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2211124722001425-fx1_lrg.jpg

- id: doi:10.1136/jitc-2023-007310
  type: paper
  image: https://www.ncbi.nlm.nih.gov/corecgi/tileshop/tileshop.fcgi?p=PMC3&id=72550&s=175&r=1&c=2

# - id: doi:10.1016/j.xcrm.2023.100938
#   type: paper
#   image: https://ars.els-cdn.com/content/image/1-s2.0-S2666379123000307-fx1_lrg.jpg

# - id: doi:10.1158/2159-8290.CD-22-1062
#   type: paper
#   image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerdiscovery/13/7/10.1158_2159-8290.cd-22-1062/4/1616fig1.jpeg?Expires=1710229248&Signature=cc81Qw6TxedEkSVVP~yVn5TsT0oWkn7KDGWBQ5LUJv9gMUHQtPVQkzZT~7w-bd3JkvAHOxlrUoqyW~UKOUGCCfkRwuDY3fvbi2aY9SuCXoGv4AlTnY2eUseLYAaMaXurmWsRmncenP-vjzeLcq6eNr5TaFreTuM9qoQxtoWTiNMMDk4dVGF0fiDb2EdsDoRpmjYA52zqvSeMiaRPy7MDRh0EoOioTGCKiADA9yx4BcVsnmFSUfDxeSTu8g4Fh~a~E-ZwYuksgD36cy5aHjk1KCzFbsLKthWDylbMaa6ZUMNXpnLmJ26gR0Q0YVhEHMoR0CBhFAwpgI6vUe5HAPhdTg__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

# - id: doi:10.1038/s41467-023-39528-9
#   type: paper
#   image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-023-39528-9/MediaObjects/41467_2023_39528_Fig1_HTML.png?as=webp

- id: doi:10.1016/j.medj.2023.12.009
  type: paper
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2666634023004075-fx1_lrg.jpg

- id: doi:10.1158/2159-8290.CD-22-0111
  type: paper
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerdiscovery/12/11/10.1158_2159-8290.cd-22-0111/3/m_2666fig1.jpeg?Expires=1681214687&Signature=mwsUxMpvii84tjc2sF5RvrSsMzkVbKQS9NKTv66npKJzxbn01VRt36DU2ip9ZlXHgHmXXAuwJrLXUfd~cm14CJlUoo7WirIWRBmfqb1lYD-AGetb~3yAXxezhG-GrX1~TcRmiCCf7DpJNQnsFB6G5jmEgbxWy5B4VM~wFZ7uAsLG7CAJP17IFcSvIy~OCdWy41zyDcxf5Sy-KbwqypfsErSvdRMBKXZZpbCgs2JqQAvvGaI-fJsBqo7tYl07wg0Q4O3BJceR7VK9Innjc5gzbtmVP7Vh5C9GSv5rUuXzq~mDWkf1LKmEfuE5yh-iKNzhgLGYffbcOM6MR30eatTg5A__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1016/j.cell.2021.03.030
  type: paper
#   description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0092867421003615-fx1.jpg
#   buttons:
#     - type: manubot
#       link: https://greenelab.github.io/meta-review/
#     - type: source
#       text: Manuscript Source
#       link: https://github.com/greenelab/meta-review
#     - type: website
#       link: http://manubot.org/
  tags:
    - synthetic lethality
    - cancer therapy
    - precision medicine
  repo: NEXGEM/SELECT
  
- id: doi:10.1038/s41467-021-21804-1
  type: paper
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-021-21804-1/MediaObjects/41467_2021_21804_Fig1_HTML.png?as=webp
  
- id: doi:10.1038/s43018-020-0106-7
  type: paper
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs43018-020-0106-7/MediaObjects/43018_2020_106_Fig1_HTML.png?as=webp
  
- id: doi:10.1038/s41467-020-14639-9
  type: paper
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-020-14639-9/MediaObjects/41467_2020_14639_Fig1_HTML.png?as=webp
   
- id: doi:10.1038/s41467-018-04647-1
  type: paper
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-018-04647-1/MediaObjects/41467_2018_4647_Fig1_HTML.jpg?as=webp
  
- id: doi:10.1016/j.ccell.2019.01.009
  type: paper
  image: https://www.cell.com/cms/attachment/6a7b8f6a-74be-40a4-85cc-d01f8e7e4ccd/fx1.jpg
  
- id: doi:10.1016/j.cell.2018.07.019
  type: paper
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0092867418309139-fx1.jpg
  
- id: doi:10.1038/s41591-018-0157-9
  type: paper
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41591-018-0157-9/MediaObjects/41591_2018_157_Fig1_HTML.png?as=webp
  
- id: doi:10.1038/s41556-019-0415-1
  type: paper
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41556-019-0415-1/MediaObjects/41556_2019_415_Fig1_HTML.png?as=webp
  
- id: doi:10.1001/jamaoncol.2019.2311
  type: paper
  image: https://cdn.jamanetwork.com/ama/content_public/journal/oncology/938270/cbr190007f1.png?Expires=1682004390&Signature=XTp2ZHqY787p4upKcKjb7af99L2ChqPLANq66Btjo7OhbLxjpxCcqNY2ZphPUl3t2iTGPs3HjAAConNnFnRiUnSHQK80hiiiFiTBrGKxC-I2oaX4VrtOxTGL~YGucVW1yEBoJyvhXaW-BVVouk565cDMiUcHHPbGIkGZ1gRxP8XQ7oUiB4iduaLsCrZiozoGvpTbOSUMV~Apy-wpuIcvQ6xB3WZ~AnoYVMeLIBRVoORUKSACdI07CEqq6y8M5FMuEUQVjB3p5vuh1fT9PQusHYi4eO9N-xbKN-JLqwcwHzRtPz-zHxhePR7qXTVpXUOqjWHo55JTquQEDkWbELS-EQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  
